spring:
  application:
    name: hello-java
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  # Kafka Configuration
  # IMPORTANT: do NOT set spring.kafka.bootstrap-servers here to localhost:9092
  # because the embedded kafka test will provide the broker address automatically.
  kafka:
    bootstrap-servers: # intentionally blank for embedded tests
    consumer:
      group-id: hello-java-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# MIDAS Topic Configuration
midas:
  topic:
    transactions: midas-transactions